config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include("user.urls", namespace="user")),
    path("post/", include("post.urls", namespace="post")),
    path("api/v1/user/", include("user.urls", namespace="user_api")),
    path("api/v1/post/", include("post.urls", namespace="post_api")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from . import views

app_name = "post"
urlpatterns = [
    path("", views.post_list, name="post_list"),
    path("<int:pk>/", views.post_detail, name="post_detail"),
    path("create/", views.post_create, name="post_create"),
    path("<int:pk>/update/", views.post_update, name="post_update"),
    path("<int:pk>/delete/", views.post_delete, name="post_delete"),
    path("<int:pk>/comment/", views.comment_create, name="comment_create"),
    path(
        "<int:pk>/comment/<int:comment_pk>/delete/",
        views.comment_delete,
        name="comment_delete",
    ),
    # path(
    #     "<int:pk>/comment/<int:comment_pk>/update/",
    #     views.comment_update,
    #     name="comment_update",
    # ),
    path("<int:pk>/like/", views.like, name="like"),
]

post/models.py
from django.db import models
from django.conf import settings


class TimeStampModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Post(TimeStampModel):
    title = models.CharField(max_length=100)
    content = models.TextField()
    author = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(
        to=settings.AUTH_USER_MODEL, related_name="like_posts"
    )

    def __str__(self):
        return self.title


class Comment(TimeStampModel):
    post = models.ForeignKey(to=Post, on_delete=models.CASCADE, related_name="comments")
    message = models.CharField(max_length=140)
    author = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.post.title}의 댓글"

post/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = "__all__"
        exclude = ("author",)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = "__all__"
        exclude = (
            "author",
            "post",
        )

post/views.py
from django.shortcuts import render, redirect
from .forms import PostForm, CommentForm
from .models import Post, Comment
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.urls import reverse


def post_list(request):
    posts = Post.objects.all().order_by("-pk")
    context = {"posts": posts}
    return render(request, "post/post_list.html", context)


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comment_form = CommentForm()
    comments = post.comments.all()
    context = {"post": post, "comment_form": comment_form, "comments": comments}
    return render(request, "post/post_detail.html", context)


@login_required
def post_create(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect("post:post_detail", post.pk)
    else:
        form = PostForm()
    context = {"form": form}
    return render(request, "post/post_form.html", context)


@login_required
def post_update(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if post.author != request.user:
        post_detail_url = reverse("post:post_detail", kwargs={"pk": pk})
        context = {"post_detail_url": post_detail_url}
        return render(request, "post/post_forbidden.html", context)

    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect("post:post_detail", post.pk)
    else:
        form = PostForm(instance=post)
    context = {"post": post, "form": form}
    return render(request, "post/post_form.html", context)


@login_required
@require_POST
def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if post.author != request.user:
        post_detail_url = reverse("post:post_detail", kwargs={"pk": pk})
        context = {"post_detail_url": post_detail_url}
        return render(request, "post/post_forbidden.html", context)
    post.delete()
    return redirect("post:post_list")


@login_required
@require_POST
def comment_create(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            return redirect("post:post_detail", post.pk)


@login_required
@require_POST
def comment_delete(request, pk, comment_pk):
    post = get_object_or_404(Post, pk=pk)
    comment = Comment.objects.get(pk=comment_pk)

    if comment.author != request.user:
        post_detail_url = reverse("post:post_detail", kwargs={"pk": pk})
        context = {"post_detail_url": post_detail_url}
        return render(request, "post/post_forbidden.html", context)
    comment.delete()
    return redirect("post:post_detail", post.pk)


def like(request, pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=pk)
        if post.like_users.filter(pk=request.user.pk).exists():
            post.like_users.remove(request.user)
        else:
            post.like_users.add(request.user)
    else:
        return redirect("user:login")

    return redirect("post:post_list")


# @login_required
# def comment_update(request, pk, comment_pk):
#     post = get_object_or_404(Post, pk=pk)
#     comments = Comment.objects.all()
#     comment = Comment.objects.get(pk=comment_pk)

#     if comment.author != request.user:
#         post_detail_url = reverse("post:post_detail", kwargs={"pk": pk})
#         context = {"post_detail_url": post_detail_url}
#         return render(request, "post/post_forbidden.html", context)

#     if request.method == "POST":
#         form = CommentForm(request.POST, instance=comment)
#         if form.is_valid():
#             comment = form.save()
#             comment.save()
#             return redirect("post:post_detail", post.pk)
#     else:
#         form = CommentForm(instance=comment)
#     context = {"post": post, "comments": comments, "comment": comment, "form": form}
#     return render(request, "post/post_detail.html", context)

post/templates/post/post_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>This is post detail page</h1>
    <p>제목 : {{ post.title }}</p>
    <p>작성자: {{ post.author }}</p>
    <p>내용: {{ post.content }}</p>
    <p>작성날짜: {{ post.created_at }}</p>
    <p>수정날짜: {{ post.updated_at }}</p>

    <a href="{% url 'post:post_update' post.pk %}">수정하기</a>
    <a href="{% url 'post:post_list' %}">목록으로</a>
    
    <form action="{% url 'post:post_delete' post.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="글 삭제">
    </form>

    <hr>
    <h3>댓글 {{ comments|length }}개</h3>
    <form action="{% url 'post:comment_create' post.pk %}" method="POST">
        {% csrf_token %}
        {{ comment_form.as_p}}
        <input type="submit" value="댓글달기">
    </form>

    <ul>
        {% for comment in comments %}
            <li>
                <p>{{ comment.author }}: {{ comment.message }}<br>{{ comment.created_at }}</p>
                <form action="{% url 'post:comment_delete' post.pk comment.pk %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="삭제">
                </form>
                {% endfor %}
            </li>
    </ul>
{% endblock content %}

post/templates/post/post_forbidden.html
{% extends "base.html" %}

{% block content %}
    <h3>권한이 없습니다.</h3>
    <a href="{{ post_detail_url }}">돌아가기</a>
{% endblock content %}

post/templates/post/post_form.html
{% extends "base.html" %}

{% block content %}
    <h1>This is post form page</h1>
    <form action="{% if post %}{% url 'post:post_update' post.pk %}{% else %}{% url 'post:post_create' %}{% endif %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">작성하기</button>
    </form>
{% endblock content %}

post/templates/post/post_list.html
{% extends "base.html" %}

{% block content %}
    <h1>This is post list page</h1>
    <a href="{% url 'post:post_create' %}">새 글 작성</a>
    <ul>
        {% for post in posts %}
        <li>
            <a href="{% url 'post:post_detail' post.pk %}">
                <div>[{{ post.created_at|date:"Y-m-d" }}] {{ post.title }}</div>
            </a>
            <form action="{% url 'post:like' post.pk %}" method="POST">
                {% csrf_token %}
                {% if user in post.like_users.all %}
                    <input type="submit" value="좋아요 취소">
                {% else %}
                    <input type="submit" value="좋아요">
                {% endif %}
            </form>
        </li>
        {% endfor %}
    </ul>
{% endblock content %}