config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include("user.urls", namespace="user")),
    path("post/", include("post.urls", namespace="post")),
    path("api/v1/user/", include("user.urls", namespace="user_api")),
    path("api/v1/post/", include("post.urls", namespace="post_api")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from . import views

app_name = "post"
urlpatterns = [
    path("", views.post_list, name="post_list"),
    path("<int:pk>/", views.post_detail, name="post_detail"),
    path("create/", views.post_create, name="post_create"),
    path("<int:pk>/update/", views.post_update, name="post_update"),
    path("<int:pk>/delete/", views.post_delete, name="post_delete"),
    path("<int:pk>/comment/", views.comment_create, name="comment_create"),
    path(
        "<int:pk>/comment/<int:comment_pk>/delete/",
        views.comment_delete,
        name="comment_delete",
    ),
    # path(
    #     "<int:pk>/comment/<int:comment_pk>/update/",
    #     views.comment_update,
    #     name="comment_update",
    # ),
    path("<int:pk>/like/", views.like, name="like"),
]

user/urls.py
from django.urls import path
from . import views

app_name = "user"
urlpatterns = [
    path("", views.user_list, name="list"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("delete/", views.delete, name="delete"),
    path("update/", views.update, name="update"),
    path("password/", views.change_password, name="change_password"),
    path("<int:pk>", views.profile, name="profile"),
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    image = models.ImageField(upload_to="user/", blank=True)
    introduction = models.TextField()

user/forms.py
from django import forms
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm as DjangoUserCreationForm
from django.contrib.auth.forms import UserChangeForm as DjangoUserChangeForm


class UserCreationForm(DjangoUserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "first_name",
            "last_name",
            "image",
            "introduction",
            "email",
        )


class UserChangeForm(DjangoUserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ("first_name", "last_name", "email", "image", "introduction")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        password = self.fields.get("password")
        if self.fields.get("password"):
            password_help_text = (
                "You can change the password " '<a href="{}">here</a>.'
            ).format(f"{reverse('user:change_password')}")
            self.fields["password"].help_text = password_help_text

user/views.py
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST
from .forms import UserCreationForm, UserChangeForm
from .models import CustomUser


def user_list(request):
    users = CustomUser.objects.all()
    context = {"users": users}
    return render(request, "user/user_list.html", context)


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect("user:list")
    else:
        form = UserCreationForm()
    context = {"form": form}
    return render(request, "user/signup.html", context)


@require_http_methods(["GET", "POST"])
def login(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            next_path = request.GET.get("next") or "user:list"
            return redirect(next_path)
    else:
        form = AuthenticationForm()
    context = {"form": form}
    return render(request, "user/login.html", context)


@login_required
@require_POST
def logout(request):
    if request.method == "POST":
        auth_logout(request)
    return redirect("user:list")


@login_required
def delete(request):
    if request.user.is_authenticated:
        request.user.delete()
        auth_logout(request)
    return redirect("user:list")


@login_required
@require_http_methods(["GET", "POST"])
def update(request):
    if request.method == "POST":
        form = UserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("user:list")
    else:
        form = UserChangeForm(instance=request.user)
    context = {"form": form}
    return render(request, "user/update.html", context)


@login_required
@require_http_methods(["GET", "POST"])
def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request=request, user=form.user)
            return redirect("user:list")
    else:
        form = PasswordChangeForm(request.user)
        context = {"form": form}
    return render(request, "user/change_password.html", context)


def profile(request, pk):
    user = get_object_or_404(CustomUser, pk=pk)
    context = {"user": user}
    return render(request, "user/profile.html", context)

user/templates/user/change_password.html
{% extends "base.html" %}

{% block content %}
    <h1>This is change password page</h1>
    <form action="{% url 'user:change_password' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">비밀번호 변경</button>
    </form>
{% endblock content %}

user/templates/user/login.html
{% extends "base.html" %}

{% block content %}
    <h1>This is login page</h1>
    <form action="#" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">로그인</button>
    </form>
{% endblock content %}

user/templates/user/profile.html
{% extends "base.html" %}

{% block content %}
    <h1>This is user profile page</h1>
    {% if user.image %}
        <img src="{{ user.image.url }}" alt="profile_image" style="max-width: 200px; height: auto;">
    {% else %}
        <p>프로필 사진이 없습니다.</p>
    {% endif %}
    <ul>
        <li>유저명 : {{ user.username }}</li>
        <li>이름: {{ user.first_name }} + {{ user.last_name }}</li>
        <li>이메일: {{ user.email }}</li>
        <li>자기소개: {{ user.introduction }}</li>
    </ul>
{% endblock content %}

user/templates/user/signup.html
{% extends "base.html" %}

{% block content %}
    <h1>This is signup page</h1>
    <form action="#" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        
        <button type="submit">생성</button>
    </form>
{% endblock content %}

user/templates/user/update.html
{% extends "base.html" %}

{% block content %}
    <h1>This is update page</h1>
    <form action="{% url 'user:update' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">정보수정</button>
    </form>
{% endblock content %}

user/templates/user/user_list.html
{% extends "base.html" %}

{% block content %}
    <h1>This is user list page</h1>
    <ul>
        {% for user in users %}
            <a href="{% url 'user:profile' user.pk %}">
                <div>[{{ user.username}}] {{ user.introduction }}</div>
            </a>
        {% endfor %}
    </ul>
{% endblock content %}