config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include("user.urls", namespace="user")),
    path("post/", include("post.urls", namespace="post")),
    path("api/v1/user/", include("user.urls", namespace="user_api")),
    path("api/v1/post/", include("post.urls", namespace="post_api")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from . import views

app_name = "post"
urlpatterns = [
    path("", views.post_list, name="post_list"),
    path("<int:pk>/", views.post_detail, name="post_detail"),
    path("create/", views.post_create, name="post_create"),
    path("<int:pk>/update/", views.post_update, name="post_update"),
    path("<int:pk>/delete/", views.post_delete, name="post_delete"),
    path("<int:pk>/comment/", views.comment_create, name="comment_create"),
    path(
        "<int:pk>/comment/<int:comment_pk>/delete/",
        views.comment_delete,
        name="comment_delete",
    ),
    # path(
    #     "<int:pk>/comment/<int:comment_pk>/update/",
    #     views.comment_update,
    #     name="comment_update",
    # ),
    path("<int:pk>/like/", views.like, name="like"),
]

user/urls.py
from django.urls import path
from . import views

app_name = "user"
urlpatterns = [
    path("", views.user_list, name="list"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("delete/", views.delete, name="delete"),
    path("update/", views.update, name="update"),
    path("password/", views.change_password, name="change_password"),
    path("<int:pk>", views.profile, name="profile"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="dynamic-links">
        {% if "post" in request.path %}
            <a href="{% url 'user:list' %}">유저 리스트 보기</a>
        {% elif "user" in request.path %}
            <a href="{% url 'post:post_list' %}">작성글 리스트 보기</a>
        {% endif %}
    </div>

    <div class="navber">
        {% if request.user.is_authenticated %}
        <h3>안녕하세요 {{ user }}님</h3>
        <a href="{% url 'user:update' %}">회원정보 수정</a>
        <form action="{% url 'user:logout' %}" method="POST">
            {% csrf_token %}
            <button type="submit">로그아웃</button>
        </form>
        <form action="{% url 'user:delete' %}" method="POST">
            {% csrf_token %}
            <button type="submit">회원탈퇴</button>
        </form>
        {% else %}
            <a href="{% url 'user:signup' %}">회원가입</a>
            <a href="{% url 'user:login' %}">로그인</a>
        {% endif %}
    </div>
    
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>